[build]
# rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg", "getrandom_backend=\"wasm_js\""
]

[env]
CFLAGS_wasm32_unknown_unknown = "-DZDICT_DISABLE_COVER"
