[build]
# rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "./scripts/zig_cc"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target_cpu=x86-64-v3"]


[target.x86_64-unknown-linux-musl]
linker = "./scripts/zig_cc"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target_cpu=x86-64-v3"]

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg", "getrandom_backend=\"wasm_js\""
]

[env]
CFLAGS_wasm32_unknown_unknown = "-DZDICT_DISABLE_COVER"
NIX_CFLAGS_COMPILE = { value = "", force = true }
